// Code generated by github.com/furu2revival/musicbox/cmd/protoc-gen-musicbox-server. DO NOT EDIT.
// source: api/debug/echo.proto

package debug

import (
	connect "connectrpc.com/connect"
	context "context"
	connect1 "github.com/furu2revival/musicbox/app/infrastructure/connect"
	aop "github.com/furu2revival/musicbox/app/infrastructure/connect/aop"
	custom_option "github.com/furu2revival/musicbox/protobuf/custom_option"
	proto "google.golang.org/protobuf/proto"
)

type musicbox_EchoServiceHandler interface {
	EchoV1(ctx context.Context, req *aop.Request[*EchoServiceEchoV1Request]) (*EchoServiceEchoV1Response, error)
}

func NewEchoServiceHandler(handler musicbox_EchoServiceHandler, proxy aop.Proxy) musicbox_EchoServiceHandlerImpl {
	service := File_api_debug_echo_proto.Services().ByName("EchoService")
	causes := [1]map[error]*aop.MethodErrDefinition{{}}
	methodOpts := [1]*aop.MethodOption{}
	for i, m := 0, service.Methods(); i < 1; i++ {
		methodOpts[i] = proto.GetExtension(m.Get(i).Options(), custom_option.E_MethodOption).(*aop.MethodOption)
	}
	methodInfo := [1]*aop.MethodInfo{
		aop.NewMethodInfo(methodOpts[0], causes[0]),
	}
	return musicbox_EchoServiceHandlerImpl{handler: handler, proxy: proxy, methodInfo: methodInfo}
}

type musicbox_EchoServiceHandlerImpl struct {
	handler    musicbox_EchoServiceHandler
	proxy      aop.Proxy
	methodInfo [1]*aop.MethodInfo
}

func (h musicbox_EchoServiceHandlerImpl) EchoV1(ctx context.Context, req *connect.Request[EchoServiceEchoV1Request]) (*connect.Response[EchoServiceEchoV1Response], error) {
	res, err := connect1.Invoke(ctx, req.Msg, req.Header(), h.methodInfo[0], h.handler.EchoV1, h.proxy)
	if err != nil {
		return nil, err
	}
	return connect.NewResponse(res), nil
}
