// @generated by protoc-gen-connect-query v0.4.1 with parameter "target=ts"
// @generated from file api/music_sheet.proto (package api, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { createQueryService } from "@bufbuild/connect-query";
import { MethodKind } from "@bufbuild/protobuf";
import {
	MusicSheetServiceCreateV1Request,
	MusicSheetServiceCreateV1Response,
	MusicSheetServiceGetV1Request,
	MusicSheetServiceGetV1Response,
} from "./music_sheet_pb.js";

export const typeName = "api.MusicSheetService";

/**
 * @generated from rpc api.MusicSheetService.GetV1
 */
export const getV1 = createQueryService({
	service: {
		methods: {
			getV1: {
				name: "GetV1",
				kind: MethodKind.Unary,
				I: MusicSheetServiceGetV1Request,
				O: MusicSheetServiceGetV1Response,
			},
		},
		typeName: "api.MusicSheetService",
	},
}).getV1;

/**
 * @generated from rpc api.MusicSheetService.CreateV1
 */
export const createV1 = createQueryService({
	service: {
		methods: {
			createV1: {
				name: "CreateV1",
				kind: MethodKind.Unary,
				I: MusicSheetServiceCreateV1Request,
				O: MusicSheetServiceCreateV1Response,
			},
		},
		typeName: "api.MusicSheetService",
	},
}).createV1;
