// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dao

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// MusicSheet is an object representing the database table.
type MusicSheet struct {
	MusicSheetID string    `boil:"music_sheet_id" json:"music_sheet_id" toml:"music_sheet_id" yaml:"music_sheet_id"`
	Title        string    `boil:"title" json:"title" toml:"title" yaml:"title"`
	CreatedAt    time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt    time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *musicSheetR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L musicSheetL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var MusicSheetColumns = struct {
	MusicSheetID string
	Title        string
	CreatedAt    string
	UpdatedAt    string
}{
	MusicSheetID: "music_sheet_id",
	Title:        "title",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
}

var MusicSheetTableColumns = struct {
	MusicSheetID string
	Title        string
	CreatedAt    string
	UpdatedAt    string
}{
	MusicSheetID: "music_sheets.music_sheet_id",
	Title:        "music_sheets.title",
	CreatedAt:    "music_sheets.created_at",
	UpdatedAt:    "music_sheets.updated_at",
}

// Generated where

var MusicSheetWhere = struct {
	MusicSheetID whereHelperstring
	Title        whereHelperstring
	CreatedAt    whereHelpertime_Time
	UpdatedAt    whereHelpertime_Time
}{
	MusicSheetID: whereHelperstring{field: "\"music_sheets\".\"music_sheet_id\""},
	Title:        whereHelperstring{field: "\"music_sheets\".\"title\""},
	CreatedAt:    whereHelpertime_Time{field: "\"music_sheets\".\"created_at\""},
	UpdatedAt:    whereHelpertime_Time{field: "\"music_sheets\".\"updated_at\""},
}

// MusicSheetRels is where relationship names are stored.
var MusicSheetRels = struct {
	Notes string
}{
	Notes: "Notes",
}

// musicSheetR is where relationships are stored.
type musicSheetR struct {
	Notes NoteSlice `boil:"Notes" json:"Notes" toml:"Notes" yaml:"Notes"`
}

// NewStruct creates a new relationship struct
func (*musicSheetR) NewStruct() *musicSheetR {
	return &musicSheetR{}
}

func (r *musicSheetR) GetNotes() NoteSlice {
	if r == nil {
		return nil
	}
	return r.Notes
}

// musicSheetL is where Load methods for each relationship are stored.
type musicSheetL struct{}

var (
	musicSheetAllColumns            = []string{"music_sheet_id", "title", "created_at", "updated_at"}
	musicSheetColumnsWithoutDefault = []string{"music_sheet_id", "title"}
	musicSheetColumnsWithDefault    = []string{"created_at", "updated_at"}
	musicSheetPrimaryKeyColumns     = []string{"music_sheet_id"}
	musicSheetGeneratedColumns      = []string{}
)

type (
	// MusicSheetSlice is an alias for a slice of pointers to MusicSheet.
	// This should almost always be used instead of []MusicSheet.
	MusicSheetSlice []*MusicSheet
	// MusicSheetHook is the signature for custom MusicSheet hook methods
	MusicSheetHook func(context.Context, boil.ContextExecutor, *MusicSheet) error

	musicSheetQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	musicSheetType                 = reflect.TypeOf(&MusicSheet{})
	musicSheetMapping              = queries.MakeStructMapping(musicSheetType)
	musicSheetPrimaryKeyMapping, _ = queries.BindMapping(musicSheetType, musicSheetMapping, musicSheetPrimaryKeyColumns)
	musicSheetInsertCacheMut       sync.RWMutex
	musicSheetInsertCache          = make(map[string]insertCache)
	musicSheetUpdateCacheMut       sync.RWMutex
	musicSheetUpdateCache          = make(map[string]updateCache)
	musicSheetUpsertCacheMut       sync.RWMutex
	musicSheetUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var musicSheetAfterSelectMu sync.Mutex
var musicSheetAfterSelectHooks []MusicSheetHook

var musicSheetBeforeInsertMu sync.Mutex
var musicSheetBeforeInsertHooks []MusicSheetHook
var musicSheetAfterInsertMu sync.Mutex
var musicSheetAfterInsertHooks []MusicSheetHook

var musicSheetBeforeUpdateMu sync.Mutex
var musicSheetBeforeUpdateHooks []MusicSheetHook
var musicSheetAfterUpdateMu sync.Mutex
var musicSheetAfterUpdateHooks []MusicSheetHook

var musicSheetBeforeDeleteMu sync.Mutex
var musicSheetBeforeDeleteHooks []MusicSheetHook
var musicSheetAfterDeleteMu sync.Mutex
var musicSheetAfterDeleteHooks []MusicSheetHook

var musicSheetBeforeUpsertMu sync.Mutex
var musicSheetBeforeUpsertHooks []MusicSheetHook
var musicSheetAfterUpsertMu sync.Mutex
var musicSheetAfterUpsertHooks []MusicSheetHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *MusicSheet) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range musicSheetAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *MusicSheet) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range musicSheetBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *MusicSheet) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range musicSheetAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *MusicSheet) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range musicSheetBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *MusicSheet) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range musicSheetAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *MusicSheet) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range musicSheetBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *MusicSheet) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range musicSheetAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *MusicSheet) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range musicSheetBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *MusicSheet) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range musicSheetAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddMusicSheetHook registers your hook function for all future operations.
func AddMusicSheetHook(hookPoint boil.HookPoint, musicSheetHook MusicSheetHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		musicSheetAfterSelectMu.Lock()
		musicSheetAfterSelectHooks = append(musicSheetAfterSelectHooks, musicSheetHook)
		musicSheetAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		musicSheetBeforeInsertMu.Lock()
		musicSheetBeforeInsertHooks = append(musicSheetBeforeInsertHooks, musicSheetHook)
		musicSheetBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		musicSheetAfterInsertMu.Lock()
		musicSheetAfterInsertHooks = append(musicSheetAfterInsertHooks, musicSheetHook)
		musicSheetAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		musicSheetBeforeUpdateMu.Lock()
		musicSheetBeforeUpdateHooks = append(musicSheetBeforeUpdateHooks, musicSheetHook)
		musicSheetBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		musicSheetAfterUpdateMu.Lock()
		musicSheetAfterUpdateHooks = append(musicSheetAfterUpdateHooks, musicSheetHook)
		musicSheetAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		musicSheetBeforeDeleteMu.Lock()
		musicSheetBeforeDeleteHooks = append(musicSheetBeforeDeleteHooks, musicSheetHook)
		musicSheetBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		musicSheetAfterDeleteMu.Lock()
		musicSheetAfterDeleteHooks = append(musicSheetAfterDeleteHooks, musicSheetHook)
		musicSheetAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		musicSheetBeforeUpsertMu.Lock()
		musicSheetBeforeUpsertHooks = append(musicSheetBeforeUpsertHooks, musicSheetHook)
		musicSheetBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		musicSheetAfterUpsertMu.Lock()
		musicSheetAfterUpsertHooks = append(musicSheetAfterUpsertHooks, musicSheetHook)
		musicSheetAfterUpsertMu.Unlock()
	}
}

// One returns a single musicSheet record from the query.
func (q musicSheetQuery) One(ctx context.Context, exec boil.ContextExecutor) (*MusicSheet, error) {
	o := &MusicSheet{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dao: failed to execute a one query for music_sheets")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all MusicSheet records from the query.
func (q musicSheetQuery) All(ctx context.Context, exec boil.ContextExecutor) (MusicSheetSlice, error) {
	var o []*MusicSheet

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dao: failed to assign all query results to MusicSheet slice")
	}

	if len(musicSheetAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all MusicSheet records in the query.
func (q musicSheetQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to count music_sheets rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q musicSheetQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dao: failed to check if music_sheets exists")
	}

	return count > 0, nil
}

// Notes retrieves all the note's Notes with an executor.
func (o *MusicSheet) Notes(mods ...qm.QueryMod) noteQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"notes\".\"music_sheet_id\"=?", o.MusicSheetID),
	)

	return Notes(queryMods...)
}

// LoadNotes allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (musicSheetL) LoadNotes(ctx context.Context, e boil.ContextExecutor, singular bool, maybeMusicSheet interface{}, mods queries.Applicator) error {
	var slice []*MusicSheet
	var object *MusicSheet

	if singular {
		var ok bool
		object, ok = maybeMusicSheet.(*MusicSheet)
		if !ok {
			object = new(MusicSheet)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeMusicSheet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeMusicSheet))
			}
		}
	} else {
		s, ok := maybeMusicSheet.(*[]*MusicSheet)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeMusicSheet)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeMusicSheet))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &musicSheetR{}
		}
		args[object.MusicSheetID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &musicSheetR{}
			}
			args[obj.MusicSheetID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`notes`),
		qm.WhereIn(`notes.music_sheet_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load notes")
	}

	var resultSlice []*Note
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice notes")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on notes")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for notes")
	}

	if len(noteAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.Notes = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &noteR{}
			}
			foreign.R.MusicSheet = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.MusicSheetID == foreign.MusicSheetID {
				local.R.Notes = append(local.R.Notes, foreign)
				if foreign.R == nil {
					foreign.R = &noteR{}
				}
				foreign.R.MusicSheet = local
				break
			}
		}
	}

	return nil
}

// AddNotes adds the given related objects to the existing relationships
// of the music_sheet, optionally inserting them as new records.
// Appends related to o.R.Notes.
// Sets related.R.MusicSheet appropriately.
func (o *MusicSheet) AddNotes(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Note) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.MusicSheetID = o.MusicSheetID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"notes\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"music_sheet_id"}),
				strmangle.WhereClause("\"", "\"", 2, notePrimaryKeyColumns),
			)
			values := []interface{}{o.MusicSheetID, rel.Index, rel.MusicSheetID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.MusicSheetID = o.MusicSheetID
		}
	}

	if o.R == nil {
		o.R = &musicSheetR{
			Notes: related,
		}
	} else {
		o.R.Notes = append(o.R.Notes, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &noteR{
				MusicSheet: o,
			}
		} else {
			rel.R.MusicSheet = o
		}
	}
	return nil
}

// MusicSheets retrieves all the records using an executor.
func MusicSheets(mods ...qm.QueryMod) musicSheetQuery {
	mods = append(mods, qm.From("\"music_sheets\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"music_sheets\".*"})
	}

	return musicSheetQuery{q}
}

// FindMusicSheet retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindMusicSheet(ctx context.Context, exec boil.ContextExecutor, musicSheetID string, selectCols ...string) (*MusicSheet, error) {
	musicSheetObj := &MusicSheet{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"music_sheets\" where \"music_sheet_id\"=$1", sel,
	)

	q := queries.Raw(query, musicSheetID)

	err := q.Bind(ctx, exec, musicSheetObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dao: unable to select from music_sheets")
	}

	if err = musicSheetObj.doAfterSelectHooks(ctx, exec); err != nil {
		return musicSheetObj, err
	}

	return musicSheetObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *MusicSheet) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dao: no music_sheets provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(musicSheetColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	musicSheetInsertCacheMut.RLock()
	cache, cached := musicSheetInsertCache[key]
	musicSheetInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			musicSheetAllColumns,
			musicSheetColumnsWithDefault,
			musicSheetColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(musicSheetType, musicSheetMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(musicSheetType, musicSheetMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"music_sheets\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"music_sheets\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dao: unable to insert into music_sheets")
	}

	if !cached {
		musicSheetInsertCacheMut.Lock()
		musicSheetInsertCache[key] = cache
		musicSheetInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the MusicSheet.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *MusicSheet) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	musicSheetUpdateCacheMut.RLock()
	cache, cached := musicSheetUpdateCache[key]
	musicSheetUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			musicSheetAllColumns,
			musicSheetPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dao: unable to update music_sheets, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"music_sheets\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, musicSheetPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(musicSheetType, musicSheetMapping, append(wl, musicSheetPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to update music_sheets row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to get rows affected by update for music_sheets")
	}

	if !cached {
		musicSheetUpdateCacheMut.Lock()
		musicSheetUpdateCache[key] = cache
		musicSheetUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q musicSheetQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to update all for music_sheets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to retrieve rows affected for music_sheets")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o MusicSheetSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dao: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), musicSheetPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"music_sheets\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, musicSheetPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to update all in musicSheet slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to retrieve rows affected all in update all musicSheet")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *MusicSheet) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dao: no music_sheets provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(musicSheetColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	musicSheetUpsertCacheMut.RLock()
	cache, cached := musicSheetUpsertCache[key]
	musicSheetUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			musicSheetAllColumns,
			musicSheetColumnsWithDefault,
			musicSheetColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			musicSheetAllColumns,
			musicSheetPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dao: unable to upsert music_sheets, could not build update column list")
		}

		ret := strmangle.SetComplement(musicSheetAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(musicSheetPrimaryKeyColumns) == 0 {
				return errors.New("dao: unable to upsert music_sheets, could not build conflict column list")
			}

			conflict = make([]string, len(musicSheetPrimaryKeyColumns))
			copy(conflict, musicSheetPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"music_sheets\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(musicSheetType, musicSheetMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(musicSheetType, musicSheetMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dao: unable to upsert music_sheets")
	}

	if !cached {
		musicSheetUpsertCacheMut.Lock()
		musicSheetUpsertCache[key] = cache
		musicSheetUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single MusicSheet record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *MusicSheet) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dao: no MusicSheet provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), musicSheetPrimaryKeyMapping)
	sql := "DELETE FROM \"music_sheets\" WHERE \"music_sheet_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to delete from music_sheets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to get rows affected by delete for music_sheets")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q musicSheetQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dao: no musicSheetQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to delete all from music_sheets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to get rows affected by deleteall for music_sheets")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o MusicSheetSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(musicSheetBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), musicSheetPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"music_sheets\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, musicSheetPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to delete all from musicSheet slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to get rows affected by deleteall for music_sheets")
	}

	if len(musicSheetAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *MusicSheet) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindMusicSheet(ctx, exec, o.MusicSheetID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *MusicSheetSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := MusicSheetSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), musicSheetPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"music_sheets\".* FROM \"music_sheets\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, musicSheetPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dao: unable to reload all in MusicSheetSlice")
	}

	*o = slice

	return nil
}

// MusicSheetExists checks if the MusicSheet row exists.
func MusicSheetExists(ctx context.Context, exec boil.ContextExecutor, musicSheetID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"music_sheets\" where \"music_sheet_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, musicSheetID)
	}
	row := exec.QueryRowContext(ctx, sql, musicSheetID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dao: unable to check if music_sheets exists")
	}

	return exists, nil
}

// Exists checks if the MusicSheet row exists.
func (o *MusicSheet) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return MusicSheetExists(ctx, exec, o.MusicSheetID)
}

// /////////////////////////////// BEGIN EXTENSIONS /////////////////////////////////
// Expose table columns
var (
	MusicSheetAllColumns            = musicSheetAllColumns
	MusicSheetColumnsWithoutDefault = musicSheetColumnsWithoutDefault
	MusicSheetColumnsWithDefault    = musicSheetColumnsWithDefault
	MusicSheetPrimaryKeyColumns     = musicSheetPrimaryKeyColumns
	MusicSheetGeneratedColumns      = musicSheetGeneratedColumns
)

// InsertAll inserts all rows with the specified column values, using an executor.
func (o MusicSheetSlice) InsertAll(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var sql string
	vals := []interface{}{}
	for i, row := range o {
		if !boil.TimestampsAreSkipped(ctx) {
			currTime := time.Now().In(boil.GetLocation())
			if row.CreatedAt.IsZero() {
				row.CreatedAt = currTime
			}
			if row.UpdatedAt.IsZero() {
				row.UpdatedAt = currTime
			}
		}

		if err := row.doBeforeInsertHooks(ctx, exec); err != nil {
			return 0, err
		}

		wl, _ := columns.InsertColumnSet(
			musicSheetAllColumns,
			musicSheetColumnsWithDefault,
			musicSheetColumnsWithoutDefault,
			queries.NonZeroDefaultSet(musicSheetColumnsWithDefault, row),
		)
		if i == 0 {
			sql = "INSERT INTO \"music_sheets\" " + "(\"" + strings.Join(wl, "\",\"") + "\")" + " VALUES "
		}
		sql += strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), len(vals)+1, len(wl))
		if i != len(o)-1 {
			sql += ","
		}
		valMapping, err := queries.BindMapping(musicSheetType, musicSheetMapping, wl)
		if err != nil {
			return 0, err
		}

		value := reflect.Indirect(reflect.ValueOf(row))
		vals = append(vals, queries.ValuesFromMapping(value, valMapping)...)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, vals)
	}

	result, err := exec.ExecContext(ctx, sql, vals...)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to insert all from musicSheet slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to get rows affected by insertall for music_sheets")
	}

	if len(musicSheetAfterInsertHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterInsertHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// UpsertAll inserts or updates all rows
// Currently it doesn't support "NoContext" and "NoRowsAffected"
func (o MusicSheetSlice) UpsertAll(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	nzDefaults := queries.NonZeroDefaultSet(musicSheetColumnsWithDefault, o[0])

	insert, _ := insertColumns.InsertColumnSet(
		musicSheetAllColumns,
		musicSheetColumnsWithDefault,
		musicSheetColumnsWithoutDefault,
		nzDefaults,
	)
	update := updateColumns.UpdateColumnSet(
		musicSheetAllColumns,
		musicSheetPrimaryKeyColumns,
	)

	if updateOnConflict && len(update) == 0 {
		return 0, errors.New("dao: unable to upsert music_sheets, could not build update column list")
	}

	conflict := conflictColumns
	if len(conflict) == 0 {
		conflict = make([]string, len(musicSheetPrimaryKeyColumns))
		copy(conflict, musicSheetPrimaryKeyColumns)
	}

	buf := strmangle.GetBuffer()
	defer strmangle.PutBuffer(buf)

	columns := "DEFAULT VALUES"
	if len(insert) != 0 {
		columns = fmt.Sprintf("(%s) VALUES %s",
			strings.Join(insert, ", "),
			strmangle.Placeholders(dialect.UseIndexPlaceholders, len(insert)*len(o), 1, len(insert)),
		)
	}

	fmt.Fprintf(
		buf,
		"INSERT INTO %s %s ON CONFLICT ",
		"\"music_sheets\"",
		columns,
	)

	if !updateOnConflict || len(update) == 0 {
		buf.WriteString("DO NOTHING")
	} else {
		buf.WriteByte('(')
		buf.WriteString(strings.Join(conflict, ", "))
		buf.WriteString(") DO UPDATE SET ")

		for i, v := range update {
			if i != 0 {
				buf.WriteByte(',')
			}
			quoted := strmangle.IdentQuote(dialect.LQ, dialect.RQ, v)
			buf.WriteString(quoted)
			buf.WriteString(" = EXCLUDED.")
			buf.WriteString(quoted)
		}
	}

	query := buf.String()
	valueMapping, err := queries.BindMapping(musicSheetType, musicSheetMapping, insert)
	if err != nil {
		return 0, err
	}

	var vals []interface{}
	for _, row := range o {
		if !boil.TimestampsAreSkipped(ctx) {
			currTime := time.Now().In(boil.GetLocation())
			if row.CreatedAt.IsZero() {
				row.CreatedAt = currTime
			}

			row.UpdatedAt = currTime
		}

		if err := row.doBeforeUpsertHooks(ctx, exec); err != nil {
			return 0, err
		}

		value := reflect.Indirect(reflect.ValueOf(row))
		vals = append(vals, queries.ValuesFromMapping(value, valueMapping)...)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, vals)
	}

	result, err := exec.ExecContext(ctx, query, vals...)
	if err != nil {
		return 0, errors.Wrap(err, "dao: unable to upsert for music_sheets")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dao: failed to get rows affected by upsert for music_sheets")
	}

	if len(musicSheetAfterUpsertHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterUpsertHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

///////////////////////////////// END EXTENSIONS /////////////////////////////////
